### PR TITLE
Improve accessibility in "Showcases" and on the player

### PR DESCRIPTION
**Pull request by MGaetan89**
# Pull request

## Description

This improves accessibility in the "Showcases" section and on the player.

## Changes made

- Adjust `PillarboxSlider` when TalkBack is enabled, i.e.:
  - Enforce non-compact mode.
  - Add vertical padding.
  - Add progress information.
- Migrate player settings to Material 3 Bottom Sheet (instead of Material Navigation Bottom Sheet). The former provides better accessibility support.
- Remove Gradle cache support in the `build_windows.yml` workflow. This action differentiates cache by platform, so this was unnecessary since we never store cache for Windows builds.

## Checklist

- [ ] APIs have been properly documented (if relevant).
- [ ] The documentation has been updated (if relevant).
- [ ] New unit tests have been written (if relevant).
- [x] The demo has been updated (if relevant).

### CODE REVIEW

**Comment by StaehliJ** [comment]
- We should remove Overlay text from TalkBack.
- TalkBack in French say "2 metres 12" instead of a time.
- The toggle controls text should be more explicite. But it is better than before.
- When double drag in TalkBack, the controls are hide but nothing tells user in has been hidden and nothing tells what to do next.

**Comment by MGaetan89** [comment]
- Check if we should lower media volume when TalkBack speaks

**Comment by MGaetan89** [comment]
> * We should remove Overlay text from TalkBack.

Done ✅

> * TalkBack in French say "2 metres 12" instead of a time.

Changed to speak out the progress in percentage instead ✅

> * The toggle controls text should be more explicite. But it is better than before.

Added an accessibility label to describe the state of the controls ("Controls visible"/"Controls hidden") ✅

> * When double drag in TalkBack, the controls are hide but nothing tells user in has been hidden and nothing tells what to do next.

I'll look into this tomorrow ⏳

> * Check if we should lower media volume when TalkBack speaks

I'll look into this tomorrow ⏳

> * Replace the emoji name with the media type

Done ✅

> * Replace URN with comment in `DemoItem` description

Done ✅

> * Increase slider height

Done ✅

**Comment by MGaetan89** [comment]
> > * Check if we should lower media volume when TalkBack speaks
> 
> I'll look into this tomorrow ⏳

Android provides dedicated volume settings for TalkBack and Media. Maybe we should just let the user/system handle that, instead of trying to manage it ourselves. What do you think?
https://support.google.com/accessibility/android/answer/6283655?hl=en#:~:text=Change%20the%20volume%20for%20TalkBack

**Review by StaehliJ — APPROVED** [review]

**Pull request merged**
