### PR TITLE
Add SAM endpoints and CH/WW locations

### PR DESCRIPTION
**Pull request by MGaetan89**
# Pull request

## Description

This PR adds the ability to select the SAM endpoints in the `Lists` section of the demo app, as well as setting the IL location to `CH` or `WW`.

## Changes made

- Rework the `DemoItem` class, so it can be distinguished between URL and URN.
- Update `PlayerModule.createRepository()` to support passing the `forceSAM` and `ilLocation` arguments, based on the desired configuration.
- Update `MainNavigation` to propose the new backend configurations.

## Checklist

- [x] Your branch has been rebased onto the `main` branch.
- [ ] APIs have been properly documented (if relevant).
- [ ] The documentation has been updated (if relevant).
- [x] New unit tests have been written (if relevant).
- [x] The demo has been updated (if relevant).
- [x] All pull request status checks pass.

### CODE REVIEW

**Comment by StaehliJ** [comment]
I think the forced location should be also set for playback (mediaComposition calls) otherwise, what is the point?

**Review by StaehliJ — CHANGES_REQUESTED** [review]
These two parameters should be also set for media playback.

**Comment by MGaetan89** [comment]
@StaehliJ this can be reviewed again now. Most of the changes are in `Playlist` and `DemoItem`, because of the change of implementation of `DemoItem`.

> [!NOTE]
> The failing Android Tests don't seem to be linked to my change. It looks like the emulator fails to start. I've restarted the build already, with the same result: https://github.com/SRGSSR/pillarbox-android/actions/runs/11290145790/job/31401749426?pr=736.
> I'll check again later to see what we can do.
> 
> ```bash
> # Run Android Tests > Launch Emulator
> sh to create a custom hardware profile? [no] [command]/usr/bin/sh -c \printf 'hw.cpu.ncore=2
> ' >> /home/runner/.android/avd/test.avd/config.ini
> /usr/bin/sh: 1: cannot create /home/runner/.android/avd/test.avd/config.ini: Directory nonexistent
> ```

**Comment by MGaetan89** [comment]
> The failing Android Tests don't seem to be linked to my change.

Indeed, the same is happening on #726: https://github.com/SRGSSR/pillarbox-android/actions/runs/11292597001/job/31409000873?pr=726
I'm investigating now to see what we can do

**Comment by MGaetan89** [comment]
The issue seems to be related to the fact that `ubuntu-latest` now points to `ubuntu-24.04` instead of `ubuntu-22.04`. Forcing `ubuntu-22.04` works as expected. We can use that for now to not block our PRs.

In the meantime, I'll investigate the difference between [`ubuntu-22.04`](https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2204-Readme.md) and [`ubuntu-24.04`](https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2404-Readme.md) to see if there's something to do on our side, or if it's an issue in the new image version.
I've opened [this ticket](https://github.com/SRGSSR/pillarbox-android/issues/747) for tracking.

**Comment by MGaetan89** [comment]
I've reverted my change to the runner.
See https://github.com/SRGSSR/pillarbox-android/issues/747#issuecomment-2410190157

**Review by StaehliJ — APPROVED** [review]

**Pull request merged**
